version: '3'

services:
  app:
    build: .
    container_name: producao-app
    ports:
      - "8081:80"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: producao-db
    environment:
      POSTGRES_DB: tabela_receita
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d